[metadata]
name = deeptag-pytorch
version = 0.1.0
description = DeepTag marker detection library (PyTorch)
long_description = file: README.md
long_description_content_type = text/markdown
author = herohuyongtao
license = MIT
url = https://github.com/herohuyongtao/deeptag-pytorch
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
include_package_data = True
python_requires = >=3.8
install_requires =
    numpy
    opencv-python
    torch

[options.package_data]
* = models/*, codebook/*, images/*, images_tag/*, fiducial_marker/*, *.json

[options.entry_points]
console_scripts =
    deeptag-test = deeptag_pytorch.cli:main
